import { Request, Response, NextFunction } from 'express';
import { verifyAdminToken } from '../services/adminService';
import { AppError } from '../utils/appError';

// Extend Express Request type to include admin info
declare global {
  namespace Express {
    interface Request {
      adminId?: string;
      adminEmail?: string;
      adminName?: string;
      adminRole?: string;
    }
  }
}

/**
 * Authentication middleware for admin routes
 * Verifies custom JWT tokens generated by admin login
 */
export const authenticateAdmin = async (
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    // Get token from Authorization header
    const authHeader = req.headers.authorization;

    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      throw new AppError('Authorization token is required', 401);
    }

    const token = authHeader.substring(7); // Remove 'Bearer ' prefix

    if (!token) {
      throw new AppError('Authorization token is required', 401);
    }

    // Verify admin token using the existing service function
    const adminData = await verifyAdminToken(token);

    // Set admin info on request for use in controllers
    req.adminId = adminData.id;
    req.adminEmail = adminData.email;
    req.adminName = adminData.name;
    req.adminRole = adminData.role;

    next();
  } catch (error) {
    if (error instanceof AppError) {
      next(error);
    } else {
      next(new AppError('Authentication failed', 401));
    }
  }
};

